services:
  my-project-with-air-1:
    image: cosmtrek/air
    # working_dir value has to be the same of mapped volume
    working_dir: /project-package
    volumes:
      - ../:/project-package/
    networks:
      static-network:
        ipv4_address: 172.20.0.10
  my-project-with-air-2:
    image: cosmtrek/air
    # working_dir value has to be the same of mapped volume
    working_dir: /project-package
    volumes:
      - ../:/project-package/
    networks:
      static-network:
        ipv4_address: 172.20.0.11


networks:
  static-network:
    name: dev_air_1
    ipam:
      config:
        - subnet: 172.20.0.0/16
